version: '3.8'

services:
  # --- AUTH DB ---
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - ./auth_service/migrations:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- COMMENT DB ---
  comment_db:
    image: postgres:15
    container_name: comment_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: comments
    ports:
      - "5434:5432"
    volumes:
      - comment_postgres_data:/var/lib/postgresql/data
      - ./comment_service/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d comments"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- gRPC AUTH SERVER ---
  grpc_auth_server:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: grpc_auth_server
    depends_on:
      - auth_db
    ports:
      - "8082:8082"
    env_file: ./auth_service/.env
    volumes:
      - ./auth_service/config/config.yml:/app/config/config.yml
    networks:
      - backend

  # --- DELIVERY DB ---
  delivery_db:
    image: postgres:15
    container_name: delivery_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: delivery
    ports:
      - "5433:5432"
    volumes:
      - delivery_postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d delivery"]
      interval: 5s
      timeout: 5s
      retries: 5

#   --- REDIS ---
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  # --- DELIVERY SERVER ---
  delivery_server:
    build:
      context: ./delivery_service
      dockerfile: Dockerfile
    container_name: delivery_server
    depends_on:
      - delivery_db
      - grpc_auth_server
    ports:
      - "8083:8083"
    env_file:
      - ./delivery_service/.env
    environment:
      DB_HOST: delivery_db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: 123
      DB_NAME: delivery
    volumes:
      - ./delivery_service/config/redis.yml:/app/config/redis.yml
      - ./delivery_service/config/config.yml:/app/config/config.yml
      - ./delivery_service/.env:/app/.env
    networks:
      - backend

  # --- COMMENT SERVER ---
  comment_server:
    build:
      context: ./comment_service
      dockerfile: Dockerfile
    container_name: comment_server
    depends_on:
      - comment_db
    ports:
      - "8084:8084"
    environment:
      DB_HOST: comment_db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: 123
      DB_NAME: comments
    networks:
      - backend

  notify:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    container_name: notification_service
    depends_on:
      - redis
    env_file:
      - ./notification_service/.env
    volumes:
      - ./notification_service/config/redis.yml:/app/config/redis.yml
      - ./notification_service/config/notify.yml:/app/config/notify.yml
      - ./notification_service/.env:/app/.env
    networks:
      - backend

volumes:
  auth_postgres_data:
  delivery_postgres_data:
  comment_postgres_data:
  redis_data:

networks:
  backend: